# Generated by Django 2.0.2 on 2018-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
